import Foundation

enum StoopBookSeed {
    static let defaultRound: VisitRound = rounds[0]
    static let activeRun: PatrolRun? = pastRounds.first { $0.isActive }

    static let kits: [VisitKit] = [
        VisitKit(id: "kit-01", kind: .cadence, title: "Cadence", summary: "Who on this round is overdue.", prompt: "Check cadence against last visit day."),
        VisitKit(id: "kit-02", kind: .windowFit, title: "Window Fit", summary: "Typed windows plus binned travel.", prompt: "Flag two stops whose windows clash."),
        VisitKit(id: "kit-03", kind: .pinTravel, title: "Pin Travel", summary: "Haversine planning bins between pins.", prompt: "Walk or drive bin from stored coordinates."),
        VisitKit(id: "kit-04", kind: .cluster, title: "Neighbourhood Cluster", summary: "Greedy groups inside a metre radius.", prompt: "Group stoops on the same block."),
        VisitKit(id: "kit-05", kind: .accessNotes, title: "Access Notes", summary: "Entry, floor, pet, and parking fields.", prompt: "Ready only when every note is filled."),
        VisitKit(id: "kit-06", kind: .roundLoad, title: "Round Load", summary: "Dwell plus travel versus morning budget.", prompt: "Sum planning minutes against the budget."),
        VisitKit(id: "kit-07", kind: .skipCost, title: "Skip Cost", summary: "Which leftover stop goes most overdue.", prompt: "Drop cost in extra overdue days.")
    ]

    static let stops: [VisitStop] = [
        VisitStop(id: "visit-01", nickname: "River Stoop 4B", lat: 39.9478, lon: -75.1842, cadenceDays: 7, lastVisitDayOffset: 5, windowStartHour: 8, windowEndHour: 11, dwellMinutes: 30, entryNote: "buzzer 4B, two long rings", floor: "1", petNote: "quiet cat, shut in bedroom", parkingNote: "west side, hydrant gap", neighbourhoodId: "place-01"),
        VisitStop(id: "visit-02", nickname: "Hill Walk-up", lat: 39.9522, lon: -75.2091, cadenceDays: 14, lastVisitDayOffset: 7, windowStartHour: 9, windowEndHour: 12, dwellMinutes: 40, entryNote: "key under green planter", floor: "2", petNote: "small dog, leash by door", parkingNote: "alley behind, tight turn", neighbourhoodId: "place-02"),
        VisitStop(id: "visit-03", nickname: "Oak Landing", lat: 39.9421, lon: -75.2072, cadenceDays: 14, lastVisitDayOffset: 10, windowStartHour: 10, windowEndHour: 13, dwellMinutes: 45, entryNote: "lockbox left of door, 7412", floor: "3", petNote: "no pet", parkingNote: "permit block 12", neighbourhoodId: "place-03"),
        VisitStop(id: "visit-04", nickname: "Maple Vestibule", lat: 39.9552, lon: -75.2010, cadenceDays: 7, lastVisitDayOffset: 14, windowStartHour: 13, windowEndHour: 16, dwellMinutes: 50, entryNote: "side gate latch sticks, lift", floor: "Garden", petNote: "bird cage on porch", parkingNote: "corner lot, driveway", neighbourhoodId: "place-04"),
        VisitStop(id: "visit-05", nickname: "Cedar Porch", lat: 39.9616, lon: -75.1962, cadenceDays: 14, lastVisitDayOffset: 18, windowStartHour: 14, windowEndHour: 17, dwellMinutes: 60, entryNote: "keypad 5520, inner door heavy", floor: "Walk-up 3", petNote: "none noted", parkingNote: "loading curb, 15 min", neighbourhoodId: "place-05"),
        VisitStop(id: "visit-06", nickname: "Pine Landing 2A", lat: 39.9484, lon: -75.1851, cadenceDays: 14, lastVisitDayOffset: 3, windowStartHour: 8, windowEndHour: 11, dwellMinutes: 30, entryNote: "buzzer 2A twice, wait", floor: "1", petNote: "cat, do not let out", parkingNote: "west side after sweep", neighbourhoodId: "place-01"),
        VisitStop(id: "visit-07", nickname: "Willow Stoop", lat: 39.9530, lon: -75.2104, cadenceDays: 7, lastVisitDayOffset: 12, windowStartHour: 9, windowEndHour: 12, dwellMinutes: 40, entryNote: "planter key, alarm pad left", floor: "2", petNote: "small dog, feeds at 9", parkingNote: "alley, watch bins", neighbourhoodId: "place-02"),
        VisitStop(id: "visit-08", nickname: "Birch Walk-up", lat: 39.9414, lon: -75.2084, cadenceDays: 14, lastVisitDayOffset: 5, windowStartHour: 10, windowEndHour: 13, dwellMinutes: 45, entryNote: "lockbox right jamb, 1907", floor: "3", petNote: "no pet", parkingNote: "permit block 12 far side", neighbourhoodId: "place-03"),
        VisitStop(id: "visit-09", nickname: "Walnut Entry", lat: 39.9558, lon: -75.2021, cadenceDays: 14, lastVisitDayOffset: 7, windowStartHour: 13, windowEndHour: 16, dwellMinutes: 50, entryNote: "call office, then buzzer 1F", floor: "1", petNote: "terrier behind gate", parkingNote: "corner lot, shaded", neighbourhoodId: "place-04"),
        VisitStop(id: "visit-10", nickname: "Spruce Court", lat: 39.9623, lon: -75.1974, cadenceDays: 7, lastVisitDayOffset: 10, windowStartHour: 14, windowEndHour: 17, dwellMinutes: 60, entryNote: "keypad 3308, stairwell B", floor: "Walk-up 3", petNote: "none noted", parkingNote: "loading curb east", neighbourhoodId: "place-05"),
        VisitStop(id: "visit-11", nickname: "Chestnut Stoop", lat: 39.9491, lon: -75.1836, cadenceDays: 14, lastVisitDayOffset: 14, windowStartHour: 8, windowEndHour: 11, dwellMinutes: 30, entryNote: "buzzer 1C, super next door", floor: "1", petNote: "quiet cat", parkingNote: "west side near ramp", neighbourhoodId: "place-01"),
        VisitStop(id: "visit-12", nickname: "Ash Landing", lat: 39.9516, lon: -75.2082, cadenceDays: 14, lastVisitDayOffset: 18, windowStartHour: 9, windowEndHour: 12, dwellMinutes: 40, entryNote: "planter key, elevator out", floor: "2", petNote: "small dog, crate", parkingNote: "alley behind fence", neighbourhoodId: "place-02"),
        VisitStop(id: "visit-13", nickname: "Poplar Walk-up", lat: 39.9428, lon: -75.2061, cadenceDays: 7, lastVisitDayOffset: 3, windowStartHour: 10, windowEndHour: 13, dwellMinutes: 45, entryNote: "lockbox, code month+day", floor: "3", petNote: "no pet", parkingNote: "permit block 9", neighbourhoodId: "place-03"),
        VisitStop(id: "visit-14", nickname: "Elm Vestibule", lat: 39.9546, lon: -75.1998, cadenceDays: 14, lastVisitDayOffset: 12, windowStartHour: 13, windowEndHour: 16, dwellMinutes: 50, entryNote: "gate latch, lift and push", floor: "Garden", petNote: "bird, cover cage", parkingNote: "corner lot by stop sign", neighbourhoodId: "place-04"),
        VisitStop(id: "visit-15", nickname: "Beech Porch", lat: 39.9610, lon: -75.1951, cadenceDays: 14, lastVisitDayOffset: 5, windowStartHour: 14, windowEndHour: 17, dwellMinutes: 60, entryNote: "keypad 7721, mail slots", floor: "Walk-up 3", petNote: "none noted", parkingNote: "loading curb, van early", neighbourhoodId: "place-05"),
        VisitStop(id: "visit-16", nickname: "Sycamore Stoop", lat: 39.9472, lon: -75.1856, cadenceDays: 7, lastVisitDayOffset: 7, windowStartHour: 8, windowEndHour: 11, dwellMinutes: 30, entryNote: "buzzer 1B, long press", floor: "1", petNote: "cat, senior", parkingNote: "west side, fire plug", neighbourhoodId: "place-01"),
        VisitStop(id: "visit-17", nickname: "Linden Walk-up", lat: 39.9536, lon: -75.2088, cadenceDays: 14, lastVisitDayOffset: 10, windowStartHour: 9, windowEndHour: 12, dwellMinutes: 40, entryNote: "planter key, door swells", floor: "2", petNote: "small dog, timid", parkingNote: "alley, tight", neighbourhoodId: "place-02"),
        VisitStop(id: "visit-18", nickname: "Hickory Landing", lat: 39.9410, lon: -75.2068, cadenceDays: 14, lastVisitDayOffset: 14, windowStartHour: 10, windowEndHour: 13, dwellMinutes: 45, entryNote: "lockbox under rail, 4415", floor: "3", petNote: "no pet", parkingNote: "permit block 12", neighbourhoodId: "place-03"),
        VisitStop(id: "visit-19", nickname: "Magnolia Stoop", lat: 39.9564, lon: -75.2004, cadenceDays: 7, lastVisitDayOffset: 18, windowStartHour: 13, windowEndHour: 16, dwellMinutes: 50, entryNote: "office first, buzzer 4D", floor: "Garden", petNote: "bird, loud mornings", parkingNote: "corner lot north", neighbourhoodId: "place-04"),
        VisitStop(id: "visit-20", nickname: "Dogwood Entry", lat: 39.9628, lon: -75.1956, cadenceDays: 14, lastVisitDayOffset: 3, windowStartHour: 14, windowEndHour: 17, dwellMinutes: 60, entryNote: "keypad 6634, push bar", floor: "Walk-up 3", petNote: "none noted", parkingNote: "loading curb west", neighbourhoodId: "place-05"),
        VisitStop(id: "visit-21", nickname: "Redbud Walk-up", lat: 39.9496, lon: -75.1849, cadenceDays: 14, lastVisitDayOffset: 12, windowStartHour: 8, windowEndHour: 11, dwellMinutes: 30, entryNote: "buzzer 2F, wait for click", floor: "1", petNote: "two cats", parkingNote: "west side by tree", neighbourhoodId: "place-01"),
        VisitStop(id: "visit-22", nickname: "Holly Court", lat: 39.9524, lon: -75.2112, cadenceDays: 7, lastVisitDayOffset: 5, windowStartHour: 9, windowEndHour: 12, dwellMinutes: 40, entryNote: "planter key, back steps", floor: "2", petNote: "small dog, barks", parkingNote: "alley, gentle slope", neighbourhoodId: "place-02"),
        VisitStop(id: "visit-23", nickname: "Ivy Landing", lat: 39.9433, lon: -75.2089, cadenceDays: 14, lastVisitDayOffset: 7, windowStartHour: 10, windowEndHour: 13, dwellMinutes: 45, entryNote: "lockbox, 7412 same box", floor: "3", petNote: "no pet", parkingNote: "permit block 9 west", neighbourhoodId: "place-03"),
        VisitStop(id: "visit-24", nickname: "Fern Stoop", lat: 39.9541, lon: -75.2016, cadenceDays: 14, lastVisitDayOffset: 10, windowStartHour: 13, windowEndHour: 16, dwellMinutes: 50, entryNote: "side gate, latch then lift", floor: "Garden", petNote: "bird, quiet", parkingNote: "corner lot south", neighbourhoodId: "place-04"),
        VisitStop(id: "visit-25", nickname: "Moss Walk-up", lat: 39.9604, lon: -75.1968, cadenceDays: 7, lastVisitDayOffset: 14, windowStartHour: 14, windowEndHour: 17, dwellMinutes: 60, entryNote: "keypad 2210, lobby right", floor: "Walk-up 3", petNote: "none noted", parkingNote: "loading curb, 20 min", neighbourhoodId: "place-05"),
        VisitStop(id: "visit-26", nickname: "Clover Stoop", lat: 39.9480, lon: -75.1829, cadenceDays: 14, lastVisitDayOffset: 18, windowStartHour: 8, windowEndHour: 11, dwellMinutes: 30, entryNote: "buzzer 3A, two flats", floor: "1", petNote: "cat on stairs", parkingNote: "west side far end", neighbourhoodId: "place-01"),
        VisitStop(id: "visit-27", nickname: "Harbor Walk-up", lat: 39.9511, lon: -75.2098, cadenceDays: 14, lastVisitDayOffset: 3, windowStartHour: 9, windowEndHour: 12, dwellMinutes: 40, entryNote: "planter key, alarm off", floor: "2", petNote: "small dog, harness", parkingNote: "alley behind gate", neighbourhoodId: "place-02"),
        VisitStop(id: "visit-28", nickname: "Bridge Landing", lat: 39.9406, lon: -75.2093, cadenceDays: 7, lastVisitDayOffset: 12, windowStartHour: 10, windowEndHour: 13, dwellMinutes: 45, entryNote: "lockbox on rail, 9084", floor: "3", petNote: "no pet", parkingNote: "permit block 12 east", neighbourhoodId: "place-03"),
        VisitStop(id: "visit-29", nickname: "Canal Stoop", lat: 39.9555, lon: -75.1989, cadenceDays: 14, lastVisitDayOffset: 5, windowStartHour: 13, windowEndHour: 16, dwellMinutes: 50, entryNote: "office rings up, then 2C", floor: "Garden", petNote: "bird by window", parkingNote: "corner lot, curb cut", neighbourhoodId: "place-04"),
        VisitStop(id: "visit-30", nickname: "Wharf Walk-up", lat: 39.9632, lon: -75.1981, cadenceDays: 14, lastVisitDayOffset: 7, windowStartHour: 14, windowEndHour: 17, dwellMinutes: 60, entryNote: "keypad 5540, stair C", floor: "Walk-up 3", petNote: "none noted", parkingNote: "loading curb north", neighbourhoodId: "place-05"),
        VisitStop(id: "visit-31", nickname: "Market Stoop 1C", lat: 39.9489, lon: -75.1862, cadenceDays: 7, lastVisitDayOffset: 10, windowStartHour: 8, windowEndHour: 11, dwellMinutes: 30, entryNote: "buzzer 1C, market side", floor: "1", petNote: "quiet cat, blind", parkingNote: "west side, market boxes", neighbourhoodId: "place-01"),
        VisitStop(id: "visit-32", nickname: "Library Walk-up", lat: 39.9539, lon: -75.2100, cadenceDays: 14, lastVisitDayOffset: 14, windowStartHour: 9, windowEndHour: 12, dwellMinutes: 40, entryNote: "planter key, side door", floor: "2", petNote: "small dog, old", parkingNote: "alley, one space", neighbourhoodId: "place-02"),
        VisitStop(id: "visit-33", nickname: "Schoolhouse Landing", lat: 39.9425, lon: -75.2054, cadenceDays: 14, lastVisitDayOffset: 18, windowStartHour: 10, windowEndHour: 13, dwellMinutes: 45, entryNote: "lockbox 2267, porch post", floor: "3", petNote: "no pet", parkingNote: "permit block 9", neighbourhoodId: "place-03"),
        VisitStop(id: "visit-34", nickname: "Chapel Stoop", lat: 39.9569, lon: -75.2018, cadenceDays: 7, lastVisitDayOffset: 3, windowStartHour: 13, windowEndHour: 16, dwellMinutes: 50, entryNote: "gate latch, oil at hinge", floor: "Garden", petNote: "bird, sings", parkingNote: "corner lot garden side", neighbourhoodId: "place-04"),
        VisitStop(id: "visit-35", nickname: "Garden Walk-up", lat: 39.9619, lon: -75.1944, cadenceDays: 14, lastVisitDayOffset: 12, windowStartHour: 14, windowEndHour: 17, dwellMinutes: 60, entryNote: "keypad 8830, courtyard", floor: "Walk-up 3", petNote: "none noted", parkingNote: "loading curb, narrow", neighbourhoodId: "place-05"),
        VisitStop(id: "visit-36", nickname: "Orchard Stoop", lat: 39.9469, lon: -75.1838, cadenceDays: 14, lastVisitDayOffset: 5, windowStartHour: 8, windowEndHour: 11, dwellMinutes: 30, entryNote: "buzzer 1A, buzzer 1B failover", floor: "1", petNote: "cat, shy", parkingNote: "west side, shade", neighbourhoodId: "place-01"),
        VisitStop(id: "visit-37", nickname: "Terrace Landing", lat: 39.9518, lon: -75.2074, cadenceDays: 7, lastVisitDayOffset: 7, windowStartHour: 9, windowEndHour: 12, dwellMinutes: 40, entryNote: "planter key, terrace door", floor: "2", petNote: "small dog, friendly", parkingNote: "alley, head in first", neighbourhoodId: "place-02"),
        VisitStop(id: "visit-38", nickname: "Courtyard 5A", lat: 39.9418, lon: -75.2098, cadenceDays: 14, lastVisitDayOffset: 10, windowStartHour: 10, windowEndHour: 13, dwellMinutes: 45, entryNote: "lockbox 5182, inside gate", floor: "3", petNote: "no pet", parkingNote: "permit block 9 east", neighbourhoodId: "place-03"),
        VisitStop(id: "visit-39", nickname: "Lantern Walk-up", lat: 39.9538, lon: -75.2002, cadenceDays: 14, lastVisitDayOffset: 14, windowStartHour: 13, windowEndHour: 16, dwellMinutes: 50, entryNote: "office buzzes up, ask for 2A", floor: "Garden", petNote: "bird, cover at night", parkingNote: "corner lot, quiet side", neighbourhoodId: "place-04"),
        VisitStop(id: "visit-40", nickname: "Clocktower Stoop", lat: 39.9608, lon: -75.1979, cadenceDays: 7, lastVisitDayOffset: 18, windowStartHour: 14, windowEndHour: 17, dwellMinutes: 60, entryNote: "keypad 1177, tower entry", floor: "Walk-up 3", petNote: "none noted", parkingNote: "loading curb, tower lane", neighbourhoodId: "place-05"),
        VisitStop(id: "visit-41", nickname: "Ferry Landing", lat: 39.9502, lon: -75.1833, cadenceDays: 14, lastVisitDayOffset: 3, windowStartHour: 8, windowEndHour: 11, dwellMinutes: 30, entryNote: "buzzer 1F, ferry side gate", floor: "1", petNote: "cat, escapes", parkingNote: "west side, gate post", neighbourhoodId: "place-01"),
        VisitStop(id: "visit-42", nickname: "North Gate Walk-up", lat: 39.9542, lon: -75.2086, cadenceDays: 14, lastVisitDayOffset: 12, windowStartHour: 9, windowEndHour: 12, dwellMinutes: 40, entryNote: "planter key, north door", floor: "2", petNote: "small dog, gentle", parkingNote: "alley, gate code 2244", neighbourhoodId: "place-02")
    ]

    static let rounds: [VisitRound] = [
        VisitRound(id: "round-01", name: "North Loop", stopIds: ["visit-01", "visit-02", "visit-03", "visit-04", "visit-05", "visit-06", "visit-07", "visit-08"], morningBudgetMinutes: 240, isDefault: true),
        VisitRound(id: "round-02", name: "River Morning", stopIds: ["visit-01", "visit-09", "visit-10", "visit-11", "visit-12", "visit-13"], morningBudgetMinutes: 210, isDefault: false),
        VisitRound(id: "round-03", name: "Hill Circuit", stopIds: ["visit-02", "visit-14", "visit-15", "visit-16", "visit-17", "visit-18"], morningBudgetMinutes: 200, isDefault: false),
        VisitRound(id: "round-04", name: "Tower Walk", stopIds: ["visit-19", "visit-20", "visit-21", "visit-22", "visit-23", "visit-24"], morningBudgetMinutes: 195, isDefault: false),
        VisitRound(id: "round-05", name: "Park Loop", stopIds: ["visit-25", "visit-26", "visit-27", "visit-28", "visit-29", "visit-30"], morningBudgetMinutes: 180, isDefault: false),
        VisitRound(id: "round-06", name: "East Afternoon", stopIds: ["visit-31", "visit-32", "visit-33", "visit-34", "visit-35", "visit-36"], morningBudgetMinutes: 205, isDefault: false),
        VisitRound(id: "round-07", name: "Night Overflow", stopIds: ["visit-03", "visit-37", "visit-38", "visit-39", "visit-40", "visit-41"], morningBudgetMinutes: 160, isDefault: false),
        VisitRound(id: "round-08", name: "Saturday Catch-up", stopIds: ["visit-42", "visit-03", "visit-08", "visit-22", "visit-35", "visit-01", "visit-16"], morningBudgetMinutes: 220, isDefault: false)
    ]

    static let places: [NeighbourhoodPlace] = [
        NeighbourhoodPlace(id: "place-01", name: "River Blocks", centerLat: 39.9484, centerLon: -75.1844, blockNote: "Stoops along the river blocks."),
        NeighbourhoodPlace(id: "place-02", name: "North Stoops", centerLat: 39.9526, centerLon: -75.2093, blockNote: "North loop walk-ups and vestibules."),
        NeighbourhoodPlace(id: "place-03", name: "Hill Grade", centerLat: 39.9419, centerLon: -75.2077, blockNote: "Hill grade landings and porches."),
        NeighbourhoodPlace(id: "place-04", name: "Oak Corridor", centerLat: 39.9553, centerLon: -75.2007, blockNote: "Oak corridor entries near the square."),
        NeighbourhoodPlace(id: "place-05", name: "Tower Flats", centerLat: 39.9618, centerLon: -75.1964, blockNote: "Tower flats and courtyard stoops.")
    ]

    static let readings: [KitReading] = [
        KitReading(id: "reading-01", kind: .cadence, readout: "River stoop overdue on Tuesday North Loop", runId: "run-01", stopIds: ["visit-01"], primaryValue: 5.0, capturedDayOffset: 2, note: "Tuesday cadence"),
        KitReading(id: "reading-02", kind: .cadence, readout: "River stoop still overdue on Thursday North Loop", runId: "run-02", stopIds: ["visit-01"], primaryValue: 6.0, capturedDayOffset: 4, note: "Thursday cadence"),
        KitReading(id: "reading-03", kind: .windowFit, readout: "Willow and Birch windows clash after walk bin", runId: "run-01", stopIds: ["visit-07", "visit-08"], primaryValue: 1.0, capturedDayOffset: 2, note: "Window clash"),
        KitReading(id: "reading-04", kind: .pinTravel, readout: "River to Maple is a walkShort planning bin", runId: "run-01", stopIds: ["visit-01", "visit-04"], primaryValue: 6.0, capturedDayOffset: 2, note: "Pin travel"),
        KitReading(id: "reading-05", kind: .cluster, readout: "North Loop same-block cluster of four stoops", runId: "run-01", stopIds: ["visit-01", "visit-02", "visit-03", "visit-04"], primaryValue: 4.0, capturedDayOffset: 2, note: "Cluster"),
        KitReading(id: "reading-06", kind: .accessNotes, readout: "River Stoop 4B access notes are ready", runId: "run-01", stopIds: ["visit-01"], primaryValue: 1.0, capturedDayOffset: 2, note: "Access ready"),
        KitReading(id: "reading-07", kind: .roundLoad, readout: "North Loop load sits under the morning budget", runId: "run-01", stopIds: ["visit-01", "visit-02", "visit-03", "visit-04", "visit-05", "visit-06", "visit-07", "visit-08"], primaryValue: 228.0, capturedDayOffset: 2, note: "Round load"),
        KitReading(id: "reading-08", kind: .skipCost, readout: "Skipping Oak Landing adds two overdue days", runId: "run-01", stopIds: ["visit-03"], primaryValue: 2.0, capturedDayOffset: 2, note: "Skip cost"),
        KitReading(id: "reading-09", kind: .cadence, readout: "Hill Walk-up is due today on Hill Circuit", runId: "run-04", stopIds: ["visit-02"], primaryValue: 0.0, capturedDayOffset: 3, note: "Hill cadence"),
        KitReading(id: "reading-10", kind: .pinTravel, readout: "Hill to Poplar is a walkLong planning bin", runId: "run-04", stopIds: ["visit-02", "visit-14"], primaryValue: 14.0, capturedDayOffset: 3, note: "Hill travel"),
        KitReading(id: "reading-11", kind: .roundLoad, readout: "River Morning is inside its 210 minute budget", runId: "run-03", stopIds: ["visit-01", "visit-09", "visit-10", "visit-11", "visit-12", "visit-13"], primaryValue: 198.0, capturedDayOffset: 5, note: "River load"),
        KitReading(id: "reading-12", kind: .cluster, readout: "River Blocks cluster inside 250 metres", runId: "run-03", stopIds: ["visit-01", "visit-09", "visit-10"], primaryValue: 3.0, capturedDayOffset: 5, note: "River cluster"),
        KitReading(id: "reading-13", kind: .accessNotes, readout: "Oak Landing parking note is filled", runId: "run-07", stopIds: ["visit-03"], primaryValue: 1.0, capturedDayOffset: 6, note: "Oak access"),
        KitReading(id: "reading-14", kind: .windowFit, readout: "Tower Walk windows stay clear after driveShort", runId: "run-05", stopIds: ["visit-19", "visit-20"], primaryValue: 0.0, capturedDayOffset: 7, note: "Tower windows"),
        KitReading(id: "reading-15", kind: .skipCost, readout: "Dropping Ferry Landing costs four extra days", runId: "run-07", stopIds: ["visit-41"], primaryValue: 4.0, capturedDayOffset: 6, note: "Overflow skip"),
        KitReading(id: "reading-16", kind: .cadence, readout: "Clocktower Stoop is ahead on Night Overflow", runId: "run-07", stopIds: ["visit-40"], primaryValue: -3.0, capturedDayOffset: 6, note: "Overflow cadence"),
        KitReading(id: "reading-17", kind: .pinTravel, readout: "Market to Library is a walkShort bin", runId: "run-06", stopIds: ["visit-31", "visit-32"], primaryValue: 6.0, capturedDayOffset: 8, note: "East travel"),
        KitReading(id: "reading-18", kind: .roundLoad, readout: "East Afternoon is 12 minutes over budget", runId: "run-06", stopIds: ["visit-31", "visit-32", "visit-33", "visit-34", "visit-35", "visit-36"], primaryValue: 217.0, capturedDayOffset: 8, note: "East load"),
        KitReading(id: "reading-19", kind: .cluster, readout: "Tower Flats group inside 300 metres", runId: "run-05", stopIds: ["visit-19", "visit-21", "visit-23"], primaryValue: 3.0, capturedDayOffset: 7, note: "Tower cluster"),
        KitReading(id: "reading-20", kind: .accessNotes, readout: "Courtyard 5A entry note is ready", runId: "run-07", stopIds: ["visit-38"], primaryValue: 1.0, capturedDayOffset: 6, note: "Courtyard access"),
        KitReading(id: "reading-21", kind: .cadence, readout: "North Gate Walk-up is overdue on Saturday", runId: "run-08", stopIds: ["visit-42"], primaryValue: 8.0, capturedDayOffset: 0, note: "Saturday cadence"),
        KitReading(id: "reading-22", kind: .pinTravel, readout: "Ferry to North Gate is a driveShort bin", runId: "run-07", stopIds: ["visit-41", "visit-42"], primaryValue: 12.0, capturedDayOffset: 6, note: "Ferry travel"),
        KitReading(id: "reading-23", kind: .windowFit, readout: "Park Loop Fern and Moss windows clash", runId: "run-05", stopIds: ["visit-24", "visit-25"], primaryValue: 1.0, capturedDayOffset: 7, note: "Park windows"),
        KitReading(id: "reading-24", kind: .skipCost, readout: "Skipping Chapel Stoop is the highest leftover cost", runId: "run-06", stopIds: ["visit-34"], primaryValue: 3.0, capturedDayOffset: 8, note: "East skip")
    ]

    static let pastRounds: [PatrolRun] = [
        PatrolRun(id: "run-01", roundId: "round-01", isActive: false, completedStopIds: ["visit-01", "visit-02", "visit-03", "visit-04", "visit-05", "visit-06", "visit-07", "visit-08"], startedDayOffset: 2, summary: "Tuesday North Loop complete"),
        PatrolRun(id: "run-02", roundId: "round-01", isActive: false, completedStopIds: ["visit-01", "visit-02", "visit-03", "visit-04", "visit-05", "visit-06"], startedDayOffset: 4, summary: "Thursday North Loop complete"),
        PatrolRun(id: "run-03", roundId: "round-02", isActive: false, completedStopIds: ["visit-01", "visit-09", "visit-10", "visit-11", "visit-12", "visit-13"], startedDayOffset: 5, summary: "River Morning complete"),
        PatrolRun(id: "run-04", roundId: "round-03", isActive: false, completedStopIds: ["visit-02", "visit-14", "visit-15", "visit-16", "visit-17", "visit-18"], startedDayOffset: 3, summary: "Hill Circuit complete"),
        PatrolRun(id: "run-05", roundId: "round-04", isActive: false, completedStopIds: ["visit-19", "visit-20", "visit-21", "visit-22", "visit-23", "visit-24"], startedDayOffset: 7, summary: "Tower Walk complete"),
        PatrolRun(id: "run-06", roundId: "round-05", isActive: false, completedStopIds: ["visit-25", "visit-26", "visit-27", "visit-28", "visit-29", "visit-30"], startedDayOffset: 7, summary: "Park Loop complete"),
        PatrolRun(id: "run-07", roundId: "round-06", isActive: false, completedStopIds: ["visit-31", "visit-32", "visit-33", "visit-34", "visit-35"], startedDayOffset: 8, summary: "East Afternoon complete"),
        PatrolRun(id: "run-08", roundId: "round-01", isActive: true, completedStopIds: ["visit-01", "visit-02", "visit-03"], startedDayOffset: 0, summary: "North Loop active circuit")
    ]

    static let comparePairs: [ComparePair] = [
        ComparePair(id: "pair-01", label: "Tuesday vs Thursday North Loop", firstReadingID: "reading-01", secondReadingID: "reading-02", isSeeded: true),
        ComparePair(id: "pair-02", label: "River vs Hill cadence", firstReadingID: "reading-11", secondReadingID: "reading-09", isSeeded: true),
        ComparePair(id: "pair-03", label: "Tower vs Park pin travel", firstReadingID: "reading-14", secondReadingID: "reading-23", isSeeded: true),
        ComparePair(id: "pair-04", label: "East vs Saturday load", firstReadingID: "reading-18", secondReadingID: "reading-21", isSeeded: true)
    ]
}
